# --- !Ups

create table "pubs" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "locations" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "pub_id" bigint  not null,
  "lat" numeric not null,
  "lng" numeric not null,
   CONSTRAINT "fk_pubs" FOREIGN KEY ("pub_id") REFERENCES "pubs"("id")
);


# --- !Downs

drop table "pubs" if exists;
drop table "locations" if exists;
