-- noinspection SqlDialectInspectionForFile

# --- !Ups

INSERT INTO "pubs" ("name") VALUES ('The Basketmakers');
INSERT INTO "pubs" ("name") VALUES ('The Lion & Lobster');
INSERT INTO "pubs" ("name") VALUES ('Bath Arms');
INSERT INTO "pubs" ("name") VALUES ('Hop Poles');
INSERT INTO "pubs" ("name") VALUES ('Northern Lights');
INSERT INTO "pubs" ("name") VALUES ('The Black Dove');
INSERT INTO "pubs" ("name") VALUES ('Seven Stars');
INSERT INTO "pubs" ("name") VALUES ('Barley Mow');
INSERT INTO "pubs" ("name") VALUES ('Shakespeares Head');
INSERT INTO "pubs" ("name") VALUES ('The Setting Sun');
INSERT INTO "pubs" ("name") VALUES ('Earth And Stars');
INSERT INTO "pubs" ("name") VALUES ('Saint James');
INSERT INTO "pubs" ("name") VALUES ('St George''s Inn');
INSERT INTO "pubs" ("name") VALUES ('Three Jolly Butchers');
INSERT INTO "pubs" ("name") VALUES ('Brighton Beer Dispensary');
INSERT INTO "pubs" ("name") VALUES ('The Font');
INSERT INTO "pubs" ("name") VALUES ('The Sidewinder');
INSERT INTO "pubs" ("name") VALUES ('Queens Arms');
INSERT INTO "pubs" ("name") VALUES ('Sussex Yeoman');
INSERT INTO "pubs" ("name") VALUES ('The Quadrant');
INSERT INTO "pubs" ("name") VALUES ('The Eddy');
INSERT INTO "pubs" ("name") VALUES ('Fiddler''s Elbow');
INSERT INTO "pubs" ("name") VALUES ('Prince Albert');
INSERT INTO "pubs" ("name") VALUES ('Great Eastern');
INSERT INTO "pubs" ("name") VALUES ('The West Hill Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Colonnade');
INSERT INTO "pubs" ("name") VALUES ('The World''s End');
INSERT INTO "pubs" ("name") VALUES ('Hand In Hand');
INSERT INTO "pubs" ("name") VALUES ('The Crescent');
INSERT INTO "pubs" ("name") VALUES ('The Ranelagh');
INSERT INTO "pubs" ("name") VALUES ('The Wick Inn');
INSERT INTO "pubs" ("name") VALUES ('The Prince George');
INSERT INTO "pubs" ("name") VALUES ('Good Companions');
INSERT INTO "pubs" ("name") VALUES ('Park Crescent');
INSERT INTO "pubs" ("name") VALUES ('Prestonville Arms');
INSERT INTO "pubs" ("name") VALUES ('post & telegraph');
INSERT INTO "pubs" ("name") VALUES ('The Chimney House');
INSERT INTO "pubs" ("name") VALUES ('The Foragers');
INSERT INTO "pubs" ("name") VALUES ('Princess Victoria');
INSERT INTO "pubs" ("name") VALUES ('The Foundry');
INSERT INTO "pubs" ("name") VALUES ('The Thomas Kemp');
INSERT INTO "pubs" ("name") VALUES ('Caroline Of Brunswick');
INSERT INTO "pubs" ("name") VALUES ('The Mucky Duck');
INSERT INTO "pubs" ("name") VALUES ('The Greys');
INSERT INTO "pubs" ("name") VALUES ('Brighton Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Better Half');
INSERT INTO "pubs" ("name") VALUES ('The Victory Inn');
INSERT INTO "pubs" ("name") VALUES ('Black Lion');
INSERT INTO "pubs" ("name") VALUES ('Wetherspoons');
INSERT INTO "pubs" ("name") VALUES ('Preston Park Tavern');
INSERT INTO "pubs" ("name") VALUES ('Marine Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Mesmerist');
INSERT INTO "pubs" ("name") VALUES ('Pump House');
INSERT INTO "pubs" ("name") VALUES ('The Cricketers');
INSERT INTO "pubs" ("name") VALUES ('Grand Central');
INSERT INTO "pubs" ("name") VALUES ('Fortune of War');
INSERT INTO "pubs" ("name") VALUES ('The Rock');
INSERT INTO "pubs" ("name") VALUES ('The Reservoir');
INSERT INTO "pubs" ("name") VALUES ('The Gladstone');
INSERT INTO "pubs" ("name") VALUES ('The Hartington');
INSERT INTO "pubs" ("name") VALUES ('The Albion');
INSERT INTO "pubs" ("name") VALUES ('The Signalman');
INSERT INTO "pubs" ("name") VALUES ('The Geese');
INSERT INTO "pubs" ("name") VALUES ('Dover Castle');
INSERT INTO "pubs" ("name") VALUES ('The Queen''s Head');
INSERT INTO "pubs" ("name") VALUES ('The Bear');
INSERT INTO "pubs" ("name") VALUES ('Gemini Beach Bar');
INSERT INTO "pubs" ("name") VALUES ('Druid''s Head');
INSERT INTO "pubs" ("name") VALUES ('The Full Moon');
INSERT INTO "pubs" ("name") VALUES ('East Street Tap');
INSERT INTO "pubs" ("name") VALUES ('Medusa Bar');
INSERT INTO "pubs" ("name") VALUES ('Evening Star');
INSERT INTO "pubs" ("name") VALUES ('Robin Hood');
INSERT INTO "pubs" ("name") VALUES ('Royal Pavilion Tavern');
INSERT INTO "pubs" ("name") VALUES ('Hare & Hounds');
INSERT INTO "pubs" ("name") VALUES ('Heart & Hand');
INSERT INTO "pubs" ("name") VALUES ('Queens Park');
INSERT INTO "pubs" ("name") VALUES ('Mitre Tavern');
INSERT INTO "pubs" ("name") VALUES ('Prince of Wales');
INSERT INTO "pubs" ("name") VALUES ('The Hobgoblin');
INSERT INTO "pubs" ("name") VALUES ('The Constant Service');
INSERT INTO "pubs" ("name") VALUES ('The PV');
INSERT INTO "pubs" ("name") VALUES ('The Bright Helm');
INSERT INTO "pubs" ("name") VALUES ('Brighton Rocks');
INSERT INTO "pubs" ("name") VALUES ('Crown & Anchor');
INSERT INTO "pubs" ("name") VALUES ('Park View');
INSERT INTO "pubs" ("name") VALUES ('Caxton Arms');
INSERT INTO "pubs" ("name") VALUES ('The Western');
INSERT INTO "pubs" ("name") VALUES ('The Hampton');
INSERT INTO "pubs" ("name") VALUES ('Royal Sovereign');
INSERT INTO "pubs" ("name") VALUES ('Round Georges');
INSERT INTO "pubs" ("name") VALUES ('Regency Tavern');
INSERT INTO "pubs" ("name") VALUES ('Pub du Vin');
INSERT INTO "pubs" ("name") VALUES ('The Eagle');
INSERT INTO "pubs" ("name") VALUES ('The Rose Hill Tavern');
INSERT INTO "pubs" ("name") VALUES ('Hanover');
INSERT INTO "pubs" ("name") VALUES ('Sir Charles Napier');
INSERT INTO "pubs" ("name") VALUES ('Fountain Head');
INSERT INTO "pubs" ("name") VALUES ('The Joker');
INSERT INTO "pubs" ("name") VALUES ('Bulldog Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Bee''s Mouth');
INSERT INTO "pubs" ("name") VALUES ('Foggs');
INSERT INTO "pubs" ("name") VALUES ('Real ale ramble');
INSERT INTO "pubs" ("name") VALUES ('Royal Oak');
INSERT INTO "pubs" ("name") VALUES ('The Globe');
INSERT INTO "pubs" ("name") VALUES ('The Sussex');
INSERT INTO "pubs" ("name") VALUES ('The Blind Busker');
INSERT INTO "pubs" ("name") VALUES ('The White Rabbit');
INSERT INTO "pubs" ("name") VALUES ('Open House');
INSERT INTO "pubs" ("name") VALUES ('Battle Of Trafalgar');
INSERT INTO "pubs" ("name") VALUES ('The Engineer');
INSERT INTO "pubs" ("name") VALUES ('Preston Brewery Tap');
INSERT INTO "pubs" ("name") VALUES ('Bedford Tavern');
INSERT INTO "pubs" ("name") VALUES ('Duke Of Wellington');
INSERT INTO "pubs" ("name") VALUES ('Horatio''s Bar');
INSERT INTO "pubs" ("name") VALUES ('Bugle Inn');
INSERT INTO "pubs" ("name") VALUES ('Chequers');
INSERT INTO "pubs" ("name") VALUES ('The Pull and Pump');
INSERT INTO "pubs" ("name") VALUES ('Mrs Fitzherberts');
INSERT INTO "pubs" ("name") VALUES ('Montpelier Public House');
INSERT INTO "pubs" ("name") VALUES ('King & Queen');
INSERT INTO "pubs" ("name") VALUES ('The Cow');
INSERT INTO "pubs" ("name") VALUES ('Branch Tavern');
INSERT INTO "pubs" ("name") VALUES ('Martha Gunn');
INSERT INTO "pubs" ("name") VALUES ('Rat & Trumpet');
INSERT INTO "pubs" ("name") VALUES ('Walmer Castle');
INSERT INTO "pubs" ("name") VALUES ('Railway Bell');
INSERT INTO "pubs" ("name") VALUES ('The Office');
INSERT INTO "pubs" ("name") VALUES ('Ali Cats');
INSERT INTO "pubs" ("name") VALUES ('The Stoneham');
INSERT INTO "pubs" ("name") VALUES ('Cobden Arms');
INSERT INTO "pubs" ("name") VALUES ('Market Inn');
INSERT INTO "pubs" ("name") VALUES ('William The Fourth');
INSERT INTO "pubs" ("name") VALUES ('The Iron Duke');
INSERT INTO "pubs" ("name") VALUES ('The Windmill');
INSERT INTO "pubs" ("name") VALUES ('Lord Nelson');
INSERT INTO "pubs" ("name") VALUES ('Master Mariner');
INSERT INTO "pubs" ("name") VALUES ('The Jolly Poacher');
INSERT INTO "pubs" ("name") VALUES ('The Druids Arms');
INSERT INTO "pubs" ("name") VALUES ('The Eclipse');
INSERT INTO "pubs" ("name") VALUES ('The Bat & Ball');
INSERT INTO "pubs" ("name") VALUES ('Katarina Harvester');
INSERT INTO "pubs" ("name") VALUES ('The Hope and Ruin');
INSERT INTO "pubs" ("name") VALUES ('The Pond');
INSERT INTO "pubs" ("name") VALUES ('The Prodigal');
INSERT INTO "pubs" ("name") VALUES ('112 Church Street');
INSERT INTO "pubs" ("name") VALUES ('Kings Arms Hotel');
INSERT INTO "pubs" ("name") VALUES ('Horse & Groom');
INSERT INTO "pubs" ("name") VALUES ('The Southover');
INSERT INTO "pubs" ("name") VALUES ('Queensbury Arms');
INSERT INTO "pubs" ("name") VALUES ('Royal Standard');
INSERT INTO "pubs" ("name") VALUES ('Marlborough Hotel');
INSERT INTO "pubs" ("name") VALUES ('North Laine Brew House');
INSERT INTO "pubs" ("name") VALUES ('O''Neills Bars');
INSERT INTO "pubs" ("name") VALUES ('Long Man Of Wilmington');
INSERT INTO "pubs" ("name") VALUES ('Yates');
INSERT INTO "pubs" ("name") VALUES ('White Horse');
INSERT INTO "pubs" ("name") VALUES ('The Dorset');
INSERT INTO "pubs" ("name") VALUES ('Easy Bar');
INSERT INTO "pubs" ("name") VALUES ('Ancient Mariner');
INSERT INTO "pubs" ("name") VALUES ('Pond Public House');
INSERT INTO "pubs" ("name") VALUES ('Cleveland Arms');
INSERT INTO "pubs" ("name") VALUES ('Craft Beer Company');
INSERT INTO "pubs" ("name") VALUES ('Bon Appetite');
INSERT INTO "pubs" ("name") VALUES ('Stanmer Park Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Mash Tun');
INSERT INTO "pubs" ("name") VALUES ('Franklin Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Cleveland');
INSERT INTO "pubs" ("name") VALUES ('The Hollingbury');
INSERT INTO "pubs" ("name") VALUES ('The Squid');
INSERT INTO "pubs" ("name") VALUES ('The Harlequin');
INSERT INTO "pubs" ("name") VALUES ('Polar Bar East');
INSERT INTO "pubs" ("name") VALUES ('Waggon & Horses');
INSERT INTO "pubs" ("name") VALUES ('Longman');
INSERT INTO "pubs" ("name") VALUES ('Farm Tavern');
INSERT INTO "pubs" ("name") VALUES ('The Urchin');
INSERT INTO "pubs" ("name") VALUES ('Hove Place');
INSERT INTO "pubs" ("name") VALUES ('Bevendean Hotel');
INSERT INTO "pubs" ("name") VALUES ('Sussex Cricketer');
INSERT INTO "pubs" ("name") VALUES ('The Tempest Inn');
INSERT INTO "pubs" ("name") VALUES ('Molly Malones');
INSERT INTO "pubs" ("name") VALUES ('The Crown');
INSERT INTO "pubs" ("name") VALUES ('The Westbourne');
INSERT INTO "pubs" ("name") VALUES ('The Grenadier');
INSERT INTO "pubs" ("name") VALUES ('The Bell');
INSERT INTO "pubs" ("name") VALUES ('Coopers Cask');
INSERT INTO "pubs" ("name") VALUES ('Exchange Inn');
INSERT INTO "pubs" ("name") VALUES ('Sussex Arms');
INSERT INTO "pubs" ("name") VALUES ('The George Payne');
INSERT INTO "pubs" ("name") VALUES ('Bow Street Runner');
INSERT INTO "pubs" ("name") VALUES ('The Sportsman');
INSERT INTO "pubs" ("name") VALUES ('Freemasons Tavern');
INSERT INTO "pubs" ("name") VALUES ('Cliftonville Inn');
INSERT INTO "pubs" ("name") VALUES ('The Palmeira');
INSERT INTO "pubs" ("name") VALUES ('Hove Park Tavern');
INSERT INTO "pubs" ("name") VALUES ('Sussex At Hove');
INSERT INTO "pubs" ("name") VALUES ('The Vault');
INSERT INTO "pubs" ("name") VALUES ('Neptune Inn');
INSERT INTO "pubs" ("name") VALUES ('The Katrina');
INSERT INTO "pubs" ("name") VALUES ('The Nevill');
INSERT INTO "pubs" ("name") VALUES ('The Seafield');



# --- !Downs

delete from "pubs";
