language: scala
jdk: oraclejdk8
sudo: false
scala:
  - 2.11.8

jobs:
  include:
    - stage: unit tests
      script: sbt test
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: brightonpubs-staging
        api_key: $HEROKU_AUTH_TOKEN
        on: deploy