language: scala
jdk: oraclejdk8
sudo: false
scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

deploy:
  provider: heroku
  api_key: $HEROKU_AUTH_TOKEN
  app:
      master: brightonpubs-staging
      production: brightonpubs-prod