language: scala
jdk: oraclejdk8
sudo: required
scala:
  - 2.11.8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

before_deploy:
  # JavaScript test and build requirements
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get -y -qq update
  - sudo apt-get -y install nodejs

deploy:
  provider: script
  script: node -v && sbt stage deployHeroku
  skip_cleanup: true
  on: deployheroku